name: Build and Publish

on:
  # run it on push to the default repository branch
  push:
    branches: [main]
  # run it during pull request
  pull_request:

jobs:
  # define job to build and publish docker image
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1
        - name: Login to DockerHub Registry
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
        - name: Build the latest Docker image
          run: docker build https://github.com/ngocnkhe15118/project3/blob/main/udagram-frontend/Dockerfile
        - name: Push the latest Docker image
          run: docker push ngocnkhe151168/udagram-reverseproxy:v3b

